### ISSUE TITLE
Incompatible with gnome 40

### ISSUE THREAD

**Issue by pitlochry** [pbxqdown/gnome-shell-extension-transparent-window#13]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: fedora 34
- **GNOME version**: gnome 40
- **Display Server(X11/Wayland)**: wayland

### Describe the problem
Extension not compatible with gnome 40. 
TypeError: Gdk.Keymap is undefined

**Comment by pbxqdown** [comment]
Thanks for reporting. It is the same issue as #6. The issue is due to gtk's poor support of wayland. The initial Gdk.Keymap is depreciated. I tried last year and didn't find a good replace method to listen to modifier-key event. It would be great if you find a appropriate way to listen to modifier-key event under wayland environment.

**Comment by topotech** [comment]
I confirm this error happens in X11 Gnome 40 on the last updates of Manjaro (Pahvo 21.1.0). The extension works perfectly, but it can't be configurable via GUI.
