### ISSUE TITLE
Save the set transparency and reload them on boot

### ISSUE THREAD

**Issue by AnuragTiwari1** [pbxqdown/gnome-shell-extension-transparent-window#7]
I have set the transparency for my editor and would like to keep it the way i have set on every boot. currently i have to set it again every time i reboot my system

**Comment by pbxqdown** [comment]
Thanks for the suggestion. I think the feature is like providing a "filter" which will modify transparency based on windows type/name, etc. In the good old days we had compiz in ubuntu for all kinds of such tricks. It might be hard to implement in a high level gnome shell plugin due to limited support from low level framework. 
For the possible implementation, i think we need to listen to windows creation event and set the window transparency if it is a match of type/name.

**Comment by AnuragTiwari1** [comment]
Thanks for replying. I will see if i can help
